#import "@preview/zebraw:0.6.3": *
#show: zebraw.with(numbering: false, lang: false)
#import "@preview/showybox:2.0.4": showybox

= Convolutional Neural Networks
Le immagini, come informazione, sono rappresentate da griglie bidimensionali di pixel, sia che questa sia monocolore o a colori. Di conseguenza, ogni pixel corrisponde rispettivamente a uno o più valori numerici. Finora abbiamo ignorato questa struttura e trattato le immagini come vettori numerici non sfruttando quindi la relazione spaziale tra i pixel. Questo approccio era però necessario per usare gli MLP. Poiché queste reti sono invarianti rispetto all'ordine delle caratteristiche potevamo ottenere risultati simili indipendentemente dal fatto che conservassimo un ordine corrispondente alla struttura spaziale dei pixel o che permutassimo i parametri della MLP. Vorremmo invece sfruttare la nostra conoscenza a priori secondo cui i pixel vicini sono tipicamente correlati tra loro in modo da costruire modelli efficienti per l'apprendimento dei dati dalle immagini.

Vediamo quindi le _Convolutional Neural Networ (CNN)_, una potente famiglia di reti neurali progettate proprio per questo scopo.

Le moderne CNN devono il loro design a spunti tratti dalla biologia, dalla teoria dei gruppi e a una buona dose di sperimentazione pratica. Oltre alla loro efficienza nella realizzazione di modelli, le CNN sono anche efficienti dal punto di vista computazionale, sia perchè richiedono un numero inferiore di parametri rispetto alle fully connected, sia perchè le convoluzioni sono facili da parallelizzare tra i core delle GPU. Di conseguenza gli esperti applicano le CNN ogni volta che è possibile.

== From Fully Connected Layers to Convolutions
Ad oggi, i modelli di cui abbiamo parlato finora sono buoni quando abbiamo a che fare con dati tabulari ovveri dati costituiti da righe corrispondenti agli esempi e colonne per le features. Con i dati tabulari, potremme prevedere che i modelli che cerchiamo possano comportare interazioni tra le features, ma non ipotizziamo a priori alcuna struttura relativa al modo in cui le features interagiscono. Tuttavia per i dati percettivi ad alta dimensionalità, tali reti prive di struttura possono diventare difficili da gestire.

Ad esempio, tornando all'esempio sulla distinzione fra gatti e cani, supponiamo di svolgere un grande lavoro nella raccolta dei dati ottenendo un set di dati annotatno composto da fotografie da un megapixel, quindi ogni input della rete ha un milione di dimensioni. Anche una riduzione a mille dimensioni nascoste richiederebbe un fully connected layer da $10^6 times 10^3 = 10^9$ parametri. A meno che non si disponga di numerose GPU super ottimizzate, l'apprendimento dei parametri potrebbe essere irrealizzabile.

Si potrebbe pensare che non è necessaria una risoluzione di un Megapixel, tuttavia sebbene potremmo cavarcela con centomila pixel, il nostro hidden layer di dimensione $1000$ sottostima il numero di unità nascoste necessarie per apprendere buone rappresentazioni delle immagini, quindi un sistema pratico richiederà comunque miliardi di parametri. Inoltre, l'apprendimento di un classificatore mediante l'adattamento a cosí tanti parametri potrebbe richiedere la raccolta di un enorme set di dati. Oggi però sappiamo che i computer li distinguono abbastanza bene (cani e gatti). Ció è dovuto al fatto che le immagini presentano una struttura ricca che può essere sfruttata sia dagli esseri umani che dai modelli di apprendimento. Le CNN rappresentano un approccio creativo adottato dall'apprendimento automatico per sfruttra alcune delle strutture note presenti nelle immagini naturali.

== Invariance
Immaginiamo di voler individuare un oggetto in un'immagine. Sembra ragionevole che, qualunque sia il metodo utilizzato per riconoscere gli oggetti, esso non debba concentrarsi eccessivamente sulla posizione precisa dell'oggetto nell'immagine. Idealmente, il nostro sistema dovrebbe sfruttare questa conoscenza. Di solito i maiali non volano e gli aerei non nuotano. Ciononostante, dovremmo comunque riconoscere un maiale se ne comparisse uno nella parte superiore dell'immagine. Possiamo trarre ispirazione dal gioco "Dov'é Waldo?". Il gioco consiste in una serie di scene caotiche dove Waldo compare da qualche parte, in genere nascosto in luoghi improbabili, l'obiettivo è appunto individuarlo. Nonostante il suo abbigliamento caratteristico ció puó rivelarsi estremamente difficile a casua del gran numero di elementi di distrazione. Tuttavia, l'aspetto di Waldo non dipende dalla sua posizione, potremmo scansionare l'immagine con un "rilevatore di Waldo" in grado di assegnare un punteggio a ciascuna area, indicando la probabilità che tale area contenga Waldo. Infatti, molti algoritmi di rilevamento e segmentazione degli oggetti si basano su questo approccio. Le CNN sistematizzano questa idea di invarianza spaziale, sfruttandola per apprendere rappresentazioni utili con un numero minore di parametri.

Ora possiamo rendere più concrete queste intuizioni elencando alcuni requisiti che guidino la progettazione di un'architettura di rete neurale adatta alla Computer Vision:
1. Nei primi livelli, la nostra rete dovrebbe rispondere in modo simile allo stesso frammento, indipendentemente dalla sua posizione nell'immagine. Questo principio è chiamato _translation invariance_.
2. Gli strati più superficiali della rete dovrebbero concentrarsi sulle regioni locali, senza tenere conto dei contenuti dell'immagine nelle regioni distanti. Questo è il _locality principle_. Infine, queste rappresentazioni locali possono essere aggregate per effettuare previsioni a livello dell'intera immagine.
3. Man mano che procediamo, gli strati più profondi dovrebbero essere in grado di cogliere caratteristiche dell'immagine a più lungo raggio, in modo simile alla visione di livello superiore presente in natura.

Vediamo come convertire tutto questo in linguaggio matematico.

== Constraining the MLP
Per cominciare possiamo considerare un MLP con immagini bidimensionali $bold(X)$ come input e le loro rappresentazioni nascoste immediate $bold(H)$ rappresentate in modo simile tramite matrici dove $bold(X)$ e $bold(H)$ hanno la stessa forma. Immaginiamo ora che non solo gli input ma anche le rappresentazioni nascoste possiedano una struttura spaziale.

Indichiamo con $[bold(X)]_(i,j)$ e $[bold(H)]_(i,j)$ il pixel alla posizione $(i,j)$ nelle rispettive matrici. Per fare in modo che ogni hidden unit riceva input da ogni pixel in input, dobbiamo smettere di usare matrici dei pesi per rappresentare i parametri e dobbiamo usare tensori dei pesi $W$ di ordine $4$. Supponiamo che $bold(U)$ contenga i bias, possiamo quindi esprimere il fully connected layer come: $ [bold(H)]_(i,j)&=[bold(U)]_(i,j) + sum_k sum_l [W]_(i,j,k,l) [bold(X)]_(k,l) \ &= [bold(U)]_(i,j) + sum_a sum_b [V]_(i,j,a,b) [bold(X)]_(i+a,j+b) $